name: 'Check updates and build'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  packages: write

jobs:
  check:
    name: Check updates
    runs-on: ubuntu-latest
    outputs:
      VERSION_UPDATED: ${{ steps.check.outputs.VERSION_UPDATED }}
      VERSION: ${{ steps.check.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout files
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: check
        name: Run check script
        run: |
          chmod +x check.sh
          ./check.sh

      - uses: actions-js/push@master
        name: Commit & Push changes
        if: steps.check.outputs.VERSION_UPDATED == 1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "ci: SOSSE updated `${{ steps.check.outputs.VERSION }}`"

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.VERSION_UPDATED == 1
    steps:
      - uses: actions/checkout@v4
        name: Checkout files
        
      - uses: actions/checkout@v4
        name: Checkout SOSSE files
        with:
          repository: 'biolds/sosse'
          ref: ${{ needs.check.outputs.VERSION }}
          path: sosse

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: linux/arm64
          context: sosse/
          file: sosse/docker/pip-base/Dockerfile
          tags: biolds/sosse:pip-base
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Copy necessary files to build Docker image
        run: |
          cp sosse/docker/run.sh sosse/debian/uwsgi.* sosse/debian/sosse.conf sosse/

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          context: sosse/
          file: sosse/docker/pip-compose/Dockerfile
          tags: |
            ghcr.io/pmh-only/sosse:latest
            ghcr.io/pmh-only/sosse:${{ needs.check.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
